Unconditionally init repo
julianxhokaxhiu/docker-lineage-cicd pull request #5
Opened 2017-12-17 22:28 UTC by lucafavatella

... by relying on `repo init` idempotency in order to prevent
incomplete or corrupted `.repo` folder to cause the step to be
skipped.

2017-12-18 23:11 UTC, julianxhokaxhiu commented
Would it slow down the process to build? That was added to avoid the super-slow init phase.

Is there a way to detect if it is corrupted? I would prefer to introduce that with an IF if possible.

2017-12-18 23:14 UTC, julianxhokaxhiu requested changes
I'm not really happy about this solution. I think a smarter solution should be found, as it may slow down the overall CI pipeline by initializing always.

2017-12-19 22:25 UTC, lucafavatella commented
Thanks for your consideration and clear explanation.

2017-12-19 22:25 UTC, closed without merging

2018-01-28 12:09 UTC, julianxhokaxhiu commented
Found a way to fix it :) https://github.com/julianxhokaxhiu/docker-lineage-cicd/commit/2d9ef11e051a8618686539877f6751c651969316